// comment
/// also comment
/* comment */

include file.class.{meathod, field};
include file;

i32 newInt = 1;
i32 newIntHex = 0x1;
i32 newIntOct = 0o1;
i32 newIntBin = 0b1;
i32 newIntChar = 'a';

i32 newArray[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

char newChar = 'a';
char newCharHex = 0x20;
char newCharOct = 0o20;
char newCharBin = 0b1010;

Utf8 newUtf8 = "hello world";
Utf16 newUtf16 = "hello world";
Utf32 newUtf32 = "hello world";

// string is utf8 by default
String newstring = "hello world";

bool newBool = false; // 0
bool otherBool = true; // 1
bool otherOtherBool = 100; // true
bool otherOtherOtherBool = -100; // true

enum Colors {
    RED,
    ORANGE,
    YELLOW,
    GREEN,
    BLUE,
    INDIGO, 
    VIOLET,
}

string newString = "Hello, zinc!";

string* pointerString = &newString;

// ~ // NOT
// & // AND
// | // OR
// ^ // XOR
// << // bitshift left
// >> // bitshift right

// err type has a message, and a error code

// standard type declarations of functions are like that of C
main(List<String> args) -> i32 {
    Color oldColr = Colors.YELLOW;
    i32 newColor = Colors.RED;

    match(newColor) {
        RED {
            println("Color is warm");
        }
        ORANGE {
            println("Color is orange");
        }
        YELLOW {
            println("Color is yellow");
        }
        _ {
            print("Not a known color")
        }
    }     

    Vec<int> newVector = {1, 2, 3};
    newVector.push_back(4);

    i32 result = Foo.divide(10, 0).catch((Err e) => {
        @print(e.message);
        // return a value of the same type
        return -1;
    });
    @assert(result != -1);

    // bubble up errors
    i32 resultDoesntCare = Foo.divide(1, 0)?;

    // smart pointers by default
    char* charString = alloc char[100]('a'); // freed when all references leave the scope
    // unsafe c-style pointers
    unsafe_ptr<char> unsafeCharString = alloc char[100]('a'); // not freed when exits scope

    // closures
    i32 closure = (i32 x) => { return x };

    // if false, the error and abort.
    assert(run_closure() == 11);

    i32 statusCode = getHttpResponse("google.com").await().catch((Err e) => {
        print("Failed to get get https response");
        return -1;
    });
    assert(statusCode != -1);

    // .await() // returns a Result<type> and starts a new thread
    // .await_timeout(i32 miliseconds) // starts a new thread and if it does not finish within a certain amount of time, kill it and return an error
    // .await_ttl(i32 miliseconds) // starts and new thread and kills it after specified time

    return 0;
}

i32 take_closure(i32 closure(i32 x)) {
    return closure(10);
}

i32 run_closure() {
    return take_closure((i32 x) => {return x + 1});
}

class Foo {
    private i32 bar;
    public i32 baz;

    protected i32 prot = 1;

    public i32 getBar() {
        return bar;
    }

    public i32 getBaz() {
        return baz;
    }

    public void setBar(i32 bar) {
        this.bar = bar;
    }
    
    // If you have a result type, you must always have an exit route and a return route.
    public Result<int> divide(i32 x, i32 y) {
        if (y == 0) {
            // the integer and the string are both optional but you must have one.
            error (1, "You can't divide by zero");
        }
        return x / y;
    }

    public Foo(i32 x, i32 y) {
        bar = x;
        baz = y;
    }

    private ~Foo() {
        bar = 0;
        baz = 0;
    }
}

class Foo2 : Foo {
    public void printProt() {
        @print(prot);
    } 
}


async i32 getHttpResponse(string url) {
    // fake networking shit
    i32 code = network.getCode(url);

    return code;
}
